### ISSUE TITLE
[ADD] 알림창 Section로직 추가

### ISSUE THREAD

**Issue by kimscastle** [DeveloperAcademy-POSTECH/MC3-Team-12-Makers#100]
## 💡 Issue
알림창 로직추가

## 📝  todo

- [ ] 알림이 없을때(긴급, 일반) 알림이 없다는 Label노출
- [ ] 긴급알림만 있을때, 일반알림만 있을때 해당 Section만 노출

**Comment by monic98** [comment]
@kimscastle 문구는 "도착한 알림이 없습니다 : )"로 해주세요!
