### ISSUE TITLE
[ADD] 알림창 Delete기능 및 Navigate기능 추가

### ISSUE THREAD

**Issue by kimscastle** [DeveloperAcademy-POSTECH/MC3-Team-12-Makers#101]
## 💡 Issue
알림창 Delete기능 및 Navigate기능 추가

## 📝  todo
- [ ] 알림 전체 삭제 기능 추가
- [ ] 일반 알림누르면 메세지View로 이동

**Comment by monic98** [comment]
@kimscastle 전체 '삭제' 아니고 전체 '읽음' 입니다! 아래 디자인입니다.
![5  알림창](https://user-images.githubusercontent.com/103012323/186085409-1264309c-2ae3-48dc-9c4d-f7b2778460a9.png)
![7  전체 읽음 표시](https://user-images.githubusercontent.com/103012323/186085422-1e71cc5b-3929-4bff-a4fb-b1d53544d8ab.png)
